//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphs.Assets.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphs.Assets.Locales.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add edge.
        /// </summary>
        internal static string AddEdge {
            get {
                return ResourceManager.GetString("AddEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacency list.
        /// </summary>
        internal static string AdjacencyList {
            get {
                return ResourceManager.GetString("AdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacency matrix.
        /// </summary>
        internal static string AdjacencyMatrix {
            get {
                return ResourceManager.GetString("AdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new graph.
        /// </summary>
        internal static string Btn_CreateGraph {
            get {
                return ResourceManager.GetString("Btn_CreateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        internal static string Cycles_tab {
            get {
                return ResourceManager.GetString("Cycles_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges list.
        /// </summary>
        internal static string EdgesList {
            get {
                return ResourceManager.GetString("EdgesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULER CYCLE.
        /// </summary>
        internal static string EulerCycle_title {
            get {
                return ResourceManager.GetString("EulerCycle_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle not exist.
        /// </summary>
        internal static string EulerCycleNotExist {
            get {
                return ResourceManager.GetString("EulerCycleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler result type:.
        /// </summary>
        internal static string EulerCycleType {
            get {
                return ResourceManager.GetString("EulerCycleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string EulerCycleUnknown {
            get {
                return ResourceManager.GetString("EulerCycleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler cycle.
        /// </summary>
        internal static string EulerCyle {
            get {
                return ResourceManager.GetString("EulerCyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler track.
        /// </summary>
        internal static string EulerTrack {
            get {
                return ResourceManager.GetString("EulerTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find_btn {
            get {
                return ResourceManager.GetString("Find_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAMILTON CYCLE.
        /// </summary>
        internal static string HamiltonCycle_title {
            get {
                return ResourceManager.GetString("HamiltonCycle_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamilton cycle not exist.
        /// </summary>
        internal static string HamiltonCycleNotExist {
            get {
                return ResourceManager.GetString("HamiltonCycleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamilton result type:.
        /// </summary>
        internal static string HamiltonCycleType {
            get {
                return ResourceManager.GetString("HamiltonCycleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string HamiltonCycleUnknown {
            get {
                return ResourceManager.GetString("HamiltonCycleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamilton cycle.
        /// </summary>
        internal static string HamiltonCyle {
            get {
                return ResourceManager.GetString("HamiltonCyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidence matrix.
        /// </summary>
        internal static string IncidenceMatrix {
            get {
                return ResourceManager.GetString("IncidenceMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices and Edges memory preview.
        /// </summary>
        internal static string MemoryView {
            get {
                return ResourceManager.GetString("MemoryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove edge.
        /// </summary>
        internal static string RemoveEdge {
            get {
                return ResourceManager.GetString("RemoveEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select graph layout alghoritm type:.
        /// </summary>
        internal static string SelectLayoutAlghoritmType {
            get {
                return ResourceManager.GetString("SelectLayoutAlghoritmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution:.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update graph.
        /// </summary>
        internal static string UpdateGraph {
            get {
                return ResourceManager.GetString("UpdateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex already exist!.
        /// </summary>
        internal static string VertexAlreadyExists_error {
            get {
                return ResourceManager.GetString("VertexAlreadyExists_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Vertex.
        /// </summary>
        internal static string VertexName {
            get {
                return ResourceManager.GetString("VertexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices list.
        /// </summary>
        internal static string VerticesList {
            get {
                return ResourceManager.GetString("VerticesList", resourceCulture);
            }
        }
    }
}
