//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphs.Assets.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Polish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Polish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphs.Assets.Locales.Polish", typeof(Polish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj krawędź.
        /// </summary>
        internal static string AddEdge {
            get {
                return ResourceManager.GetString("AddEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista sąsiedztwa.
        /// </summary>
        internal static string AdjacencyList {
            get {
                return ResourceManager.GetString("AdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macierz sąsiedztwa.
        /// </summary>
        internal static string AdjacencyMatrix {
            get {
                return ResourceManager.GetString("AdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowy graf.
        /// </summary>
        internal static string Btn_CreateGraph {
            get {
                return ResourceManager.GetString("Btn_CreateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista krawędzi.
        /// </summary>
        internal static string EdgesList {
            get {
                return ResourceManager.GetString("EdgesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macierz incydencji.
        /// </summary>
        internal static string IncidenceMatrix {
            get {
                return ResourceManager.GetString("IncidenceMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd pamięci wierzchołków i krawędzi.
        /// </summary>
        internal static string MemoryView {
            get {
                return ResourceManager.GetString("MemoryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń krawędź.
        /// </summary>
        internal static string RemoveEdge {
            get {
                return ResourceManager.GetString("RemoveEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz algorytm rysowania grafów:.
        /// </summary>
        internal static string SelectLayoutAlghoritmType {
            get {
                return ResourceManager.GetString("SelectLayoutAlghoritmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaktualizuj graf.
        /// </summary>
        internal static string UpdateGraph {
            get {
                return ResourceManager.GetString("UpdateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wierzchołek już istnieje!.
        /// </summary>
        internal static string VertexAlreadyExists_error {
            get {
                return ResourceManager.GetString("VertexAlreadyExists_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wierzchołka.
        /// </summary>
        internal static string VertexName {
            get {
                return ResourceManager.GetString("VertexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wierzchołków.
        /// </summary>
        internal static string VerticesList {
            get {
                return ResourceManager.GetString("VerticesList", resourceCulture);
            }
        }
    }
}
